Lesson24/MVC_legacy/5. Many To Many/CodeFirst/ManyToManyExample1/ManyToManyExample1/Models/Language.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ManyToManyExample1.Models
{
    public class Language
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Continent> Continents { get; set; }
    }
}

Lesson24/MVC_legacy/5. Many To Many/CodeFirst/ManyToManyExample1/ManyToManyExample1/Controllers/ContinentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ManyToManyExample1.Models;

namespace ManyToManyExample1.Controllers
{
    public class ContinentController : Controller
    {
        private LanguageContext db = new LanguageContext();

        //
        // GET: /Continent/

        public ActionResult Index()
        {
            return View(db.Continents.ToList());
        }

        //
        // GET: /Continent/Details/5

        public ActionResult Details(int id = 0)
        {
            Continent continent = db.Continents.Find(id);
            if (continent == null)
            {
                return HttpNotFound();
            }
            return View(continent);
        }

        //
        // GET: /Continent/Create

        public ActionResult Create()
        {
            ViewBag.Languages = db.Languages.ToList();
            return View();
        }

        //
        // POST: /Continent/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Continent continent, string[] selectedLanguages)
        {
            if (ModelState.IsValid)
            {
                // проверяем на наличие в массиве continents идентификаторов континентов
                if (selectedLanguages != null)
                {
                    continent.Languages = new List<Language>();
                    foreach (var lang in db.Languages)
                    {
                        if (selectedLanguages.Contains(lang.Id.ToString()))
                        {
                            continent.Languages.Add(lang);
                        }
                    }
                }
                db.Continents.Add(continent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(continent);
        }

        //
        // GET: /Continent/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Continent continent = db.Continents.Find(id);
            if (continent == null)
            {
                return HttpNotFound();
            }
            ViewBag.Languages = db.Languages.ToList();
            return View(continent);
        }

        //
        // POST: /Continent/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Continent continent, string[] selectedLanguages)
        {
            if (ModelState.IsValid)
            {
                Continent newContinent = db.Continents.Find(continent.Id);
                newContinent.Name = continent.Name;

                // проверяем на наличие в массиве languages идентификаторов языков
                if (selectedLanguages != null)
                {
                    var languagesContinents = new HashSet<int>(newContinent.Languages.Select(lang => lang.Id));
                    foreach (var lang in db.Languages)
                    {
                        if (selectedLanguages.Contains(lang.Id.ToString()))
                        {
                            if (!languagesContinents.Contains(lang.Id))
                                newContinent.Languages.Add(lang);
                        }
                        else
                        {
                            if (languagesContinents.Contains(lang.Id))
                                newContinent.Languages.Remove(lang);
                        }
                    }
                }
                else
                {
                    newContinent.Languages.Clear();
                }

                db.Entry(newContinent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(continent);
        }

        //
        // GET: /Continent/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Continent continent = db.Continents.Find(id);
            if (continent == null)
            {
                return HttpNotFound();
            }
            return View(continent);
        }

        //
        // POST: /Continent/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Continent continent = db.Continents.Find(id);
            db.Continents.Remove(continent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Lesson24/MVC_legacy/5. Many To Many/CodeFirst/ManyToManyExample1/ManyToManyExample1/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ManyToManyExample1.Models;

namespace ManyToManyExample1.Controllers
{
    public class LanguageController : Controller
    {
        private LanguageContext db = new LanguageContext();

        //
        // GET: /Language/

        public ActionResult Index()
        {
            return View(db.Languages.ToList());
        }

        //
        // GET: /Language/Details/5

        public ActionResult Details(int id = 0)
        {
            Language language = db.Languages.Find(id);
            if (language == null)
            {
                return HttpNotFound();
            }
            return View(language);
        }

        //
        // GET: /Language/Create

        public ActionResult Create()
        {
            ViewBag.Continents = db.Continents.ToList();
            return View();
        }

        //
        // POST: /Language/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Language language, string[] selectedContinents)
        {
            if (ModelState.IsValid)
            {
                // проверяем на наличие в массиве continents идентификаторов континентов
                if (selectedContinents != null)
                {
                    language.Continents = new List<Continent>();
                    foreach (var c in db.Continents)
                    {
                        if (selectedContinents.Contains(c.Id.ToString()))
                        {
                            language.Continents.Add(c);
                        }
                    }
                }
                db.Languages.Add(language);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(language);
        }

        //
        // GET: /Language/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Language language = db.Languages.Find(id);
            if (language == null)
            {
                return HttpNotFound();
            }
            ViewBag.Continents = db.Continents.ToList();
            return View(language);
        }

        //
        // POST: /Language/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Language language, string[] selectedContinents)
        {
            if (ModelState.IsValid)
            {
                Language newLanguage = db.Languages.Find(language.Id);
                newLanguage.Name = language.Name;

                // проверяем на наличие в массиве continents идентификаторов континентов
                if (selectedContinents != null)
                {
                    var languagesContinents = new HashSet<int>(newLanguage.Continents.Select(c => c.Id));
                    foreach (var c in db.Continents)
                    {
                        if (selectedContinents.Contains(c.Id.ToString()))
                        {
                            if (!languagesContinents.Contains(c.Id))
                                newLanguage.Continents.Add(c);
                        }
                        else
                        {
                            if (languagesContinents.Contains(c.Id))
                                newLanguage.Continents.Remove(c);
                        }
                    }
                }
                else
                {
                    newLanguage.Continents.Clear();
                }

                db.Entry(newLanguage).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(language);
        }

        //
        // GET: /Language/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Language language = db.Languages.Find(id);
            if (language == null)
            {
                return HttpNotFound();
            }
            return View(language);
        }

        //
        // POST: /Language/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Language language = db.Languages.Find(id);
            db.Languages.Remove(language);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Lesson24/MVC_legacy/5. Many To Many/CodeFirst/ManyToManyExample1/ManyToManyExample1/Views/Language/Create.cshtml
@using ManyToManyExample1.Models
@model ManyToManyExample1.Models.Language

@{
    ViewBag.Title = "Create";
}

<h2>Добавление нового языка</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Язык</legend>

        <div class="editor-label"><b>Название</b></div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
        </div>

        <div class="editor-label"><b>Континенты</b></div>
        @{
            List<Continent> continents = ViewBag.Continents;
            foreach (Continent c in continents)
            {
                <input type="checkbox" name="selectedContinents" value="@c.Id" />@c.Name <br />
            }
        }
        <p>
            <input type="submit" value="Сохранить" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Вернуться к списку языков", "Index")
</div>

Lesson24/MVC_legacy/5. Many To Many/CodeFirst/ManyToManyExample1/ManyToManyExample1/Views/Language/Delete.cshtml
@model ManyToManyExample1.Models.Language

@{
    ViewBag.Title = "Delete";
}

<h2>Удаление языка</h2>

<h3>Вы действительно хотите удалить язык?</h3>
<fieldset>
    <legend>Язык</legend>

    <div class="display-label">
       <b>Название</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Удалить" /> |
        @Html.ActionLink("Вернуться к списку языков", "Index")
    </p>
}

Lesson24/MVC_legacy/5. Many To Many/CodeFirst/ManyToManyExample1/ManyToManyExample1/Views/Language/Details.cshtml
@using ManyToManyExample1.Models
@model ManyToManyExample1.Models.Language

@{
    ViewBag.Title = "Details";
}

<h2>Подробности</h2>

<fieldset>
    <legend>Информация о языке</legend>

    <div class="display-label"><b>Название</b></div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label"><b>Континенты</b></div>
    <ul>
        @foreach (Continent c in Model.Continents)
        {
            <li>@c.Name</li>
        }
    </ul>

</fieldset>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Вернуться к списку языков", "Index")
</p>

Lesson24/MVC_legacy/5. Many To Many/CodeFirst/ManyToManyExample1/ManyToManyExample1/Views/Language/Edit.cshtml
@using ManyToManyExample1.Models
@model ManyToManyExample1.Models.Language

@{
    ViewBag.Title = "Edit";
}

<h2>Редактирование языка</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Язык</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label"><b>Название</b></div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
        </div>

        <div class="editor-label"><b>Континенты</b></div>
        @{
            List<Continent> continents = ViewBag.Continents;
            foreach (Continent c in continents)
            {
                <input type="checkbox" name="selectedContinents" value="@c.Id"
                       @(Model.Continents.Contains(c) ? "checked=\"checked\"" : "") />@c.Name <br />
            }
         }
        <p>
            <input type="submit" value="Сохранить" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Вернуться к списку языков", "Index")
</div>

Lesson24/MVC_legacy/5. Many To Many/CodeFirst/ManyToManyExample1/ManyToManyExample1/Views/Language/Index.cshtml
@model IEnumerable<ManyToManyExample1.Models.Language>

@{
    ViewBag.Title = "Index";
}

<h2>Список языков</h2>

<p>
    @Html.ActionLink("Добавить язык", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Просмотреть", "Details", new { id=item.Id }) |
            @Html.ActionLink("Удалить", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
<p>
    @Html.ActionLink("Список континентов", "Index", "Continent")
</p>